### ISSUE TITLE
Extra space in the test?

### ISSUE THREAD

**Issue by saaaaaaaaaahil** [jmcgeheeiv/yamlmod#2]
Is there supposed to be a blank line at line 64 of the test?

**Comment by jmcgeheeiv** [comment]
Well done.  No, there should not be a blank line.  I should clarify my thinking underlying the solution.  I would be satisfied if I were to read my `out_yaml` using PyYaml, and then I were to read whatever `out_yaml` you obtain, the two Python data structures would be equivalent.

Therefore you are free to rearrange the order and white space in `out_yaml` as you see fit, as it will have no effect on the data structure rendered.

**Comment by jmcgeheeiv** [comment]
When you are satisfied with the solution to an issue, you should close it.  Hint, hint.
